# Generated by Django 3.0.2 on 2020-01-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200126_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='total_score',
            field=models.FloatField(default=0.0),
        ),
    ]
