# Generated by Django 3.0.2 on 2020-01-25 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('question_text', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('sample_code', models.TextField()),
                ('answer_code', models.TextField()),
                ('test_expression', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), default=list, null=True, size=None)),
                ('test_value', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), default=list, null=True, size=None)),
                ('max_score', models.FloatField(default=100.0)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('due_date', models.DateTimeField(verbose_name='due date')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial', models.PositiveIntegerField(default=0)),
                ('answer_code', models.TextField(blank=True)),
                ('test_value', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), default=list, null=True, size=None)),
                ('score', models.FloatField(default=0)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date updated')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('question', 'user')},
            },
        ),
    ]
